Dev/add multiplayer
cgewert/phaser-soccer pull request #7
Opened 2021-09-22 19:32 UTC by cgewert

No multiplayer features here :(
Just debug features implemented!

2021-09-22 19:34 UTC, cgewert commented on tsconfig.json
> +    "target": "ES2020"                     /* Zeus forgot this. */
My mistake should be ES2015

2021-09-22 23:02 UTC, l4desu-mizu requested changes

2021-09-22 23:02 UTC, l4desu-mizu commented on src/scenes/scene.ts
> +		this.ball.sprite.setVelocity(25 * direction.x, 25 * direction.y);
Phaser has a physics engine-thingy, correct?
except for blocking is there some sort of bouncy-ness? could you use an acceleration here? would the acceleration drop due to friction?

2021-09-23 17:41 UTC, cgewert commented on tsconfig.json
> +    "target": "ES2020"                     /* Zeus forgot this. */
reverted

2021-09-23 17:49 UTC, cgewert commented on src/ball.ts
> +    private owner: Player | null;
IMHO not an optional but a property able to receive values from type Player or null.
If you declare it to be optional allowed values must be Player or undefined. Because setting a value to undefined is considered bad practice in JS you could only set Player values and therefore lose the ability to delete the owner of a ball instance.

2021-09-23 18:09 UTC, cgewert commented on src/base/debug-game-object.ts
> +export class DebugGameObject{
I totally agree with you , but for now i want to use this implementation!

2021-09-23 18:10 UTC, cgewert commented on src/base/debug-game-object.ts
> +    public get textPosition() {
Absolutely not, but for convenience purposes yes!

2021-09-23 18:10 UTC, cgewert commented on src/ball.ts
> +        return Number.parseInt(this.sprite.x.toFixed(0));
Yes, it was late.

2021-09-23 18:37 UTC, cgewert commented on src/ball.ts
> +        return Number.parseInt(this.sprite.x.toFixed(0));
Done

2021-09-23 18:38 UTC, cgewert commented on src/player.ts
> +    public update() {
Your thoughts are full of wisdom

2021-09-23 18:38 UTC, cgewert commented on src/scenes/scene.ts
> +	private inputKeys: Array<GameInput> = [];
Afterwards

2021-09-23 18:40 UTC, cgewert commented on src/scenes/scene.ts
> +		// How to move the ball !???!
Yeah thats exactly what i mentioned in my stream yesterday. This is experimental and this logic will be refactored to the Player or the Ball class (or both) with upcoming pull requests.

2021-09-23 18:45 UTC, cgewert commented on src/scenes/scene.ts
> +			let newPlayer = new Player(this, newPlayerPhysics)
Because we refactored the Objects in other modules they don't know the scene they belong to, thats why the class constructor gets a this pointer referencing the scene. I don't have a good idea at this point for a better pattern.

2021-09-23 18:47 UTC, BurnySc2 commented on src/scenes/scene.ts
> +			this.shoot(this.players[0], direction);
There is no check here for if the player has possession of the ball.

2021-09-23 18:47 UTC, cgewert commented on src/scenes/scene.ts
> +		const right = this.inputKeys.find((value, idx, obj) => {return value.name === PlayerActions.move_right})?.inputKey
Another thing i mentioned yesterday, we will refactor this functionality with upcoming PRs, but for now its okay because we have so  few input keys.

2021-09-23 18:49 UTC, cgewert commented on src/scenes/scene.ts
> +		this.ball.sprite.setVelocity(25 * direction.x, 25 * direction.y);
We already use exactly the mentioned properties: bounce is 0.5, acceleration will be investigated in further pull requests.
Friction is 1.

2021-09-23 18:49 UTC, cgewert commented on src/scenes/scene.ts
> +			this.shoot(this.players[0], direction);
Thats what i told you a few minutes ago.

2021-09-23 18:51 UTC, BurnySc2 approved these changes

2021-09-23 19:26 UTC, BurnySc2 approved these changes

2021-09-23 19:29 UTC, BurnySc2 submitted a review, later dismissed

2021-09-23 20:11 UTC, l4desu-mizu commented on src/scenes/scene.ts
> +			let newPlayer = new Player(this, newPlayerPhysics)
I will hopefully propose something in a seperate pull request, then. We'll see.

2021-09-23 20:15 UTC, BurnySc2 approved these changes

2021-09-23 20:15 UTC, BurnySc2 approved these changes

2021-09-23 20:16 UTC, l4desu-mizu commented on src/ball.ts
> +    private owner: Player | null;
I'd still consider it an optional and ? tests afaik for null or undefined.
Generally speaking an optional is something that is either there or not: Marking something as "nullpointable" instead of always expecting something to be null it would indicate where you would expect a null value. however, the code is equivalent for me.

2021-09-23 20:16 UTC, merged

2021-09-23 20:17 UTC, l4desu-mizu commented on src/scenes/scene.ts
> +		this.ball.sprite.setVelocity(25 * direction.x, 25 * direction.y);
cool